[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
flow_testnet = "${FLOW_EVM_TESTNET_RPC_URL}"

# [etherscan]
# flow_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://evm-testnet.flowscan.io" }
